### ISSUE TITLE
Criar componente de modal genérico

### ISSUE THREAD

**Issue by cicerohen** [reactjs-ceara/portal-frontend#5]
Criar componente de modal genérico baseado em Radix e seguindo os padrões do nosso projeto 

https://www.radix-ui.com/primitives/docs/components/dialog

**Comment by FalaAiMatheus** [comment]
@cicerohen existe algum modelo posto já?

**Comment by cicerohen** [comment]
@FalaAiMatheus modal com  title, description e botao de fechar
